[bumpver]
current_version = "v23.0"
version_pattern = "vYY.PATCH"
commit_message = "bump version -> {new_version}"
commit = true
tag = true
push = true

[bumpver.file_patterns]
"webtex_render/main.go" = [
    'const VERSION = "{version}"',
]
"bumpver.toml" = [
    'current_version = "{version}"',
]

